FROM ubuntu:eoan


RUN apt-get -yq update

RUN apt-get -yq install \
  build-essential \
  libcups2-dev \
  libavahi-client-dev \
  git \
  bzr

RUN apt-get -yq install nano curl wget

RUN apt-get -yq install golang

